name: Example py
on:
  push:
    paths:
      - 'src/module.py'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest nose
      - name: Execute pytest
        run: pytest test/test_module.py
